spring:
  profiles:
    active: local

auth0:
  domain: dev-y3883jpsf8nhsfif.us.auth0.com
  clientId: tB9d9M0GOOexyDBlvTg4GzIZGEYjUscC
  clientSecret: 5d1VXlYQbO65WxZnFYOpGmaKebmYlqq3lmCUDdW7Fk2SGSHqpb6-pBjB5eCBU3yx
  audience: https://dev-y3883jpsf8nhsfif.us.auth0.com/api/v2/
