version: '3.8'

services:
  activity-service:
    build: ./activity-service
    container_name: activity-service
    ports:
      - "8082:8080"   # expõe a API no localhost:8082
#    depends_on:
#      redis:
#        condition: service_healthy
    networks:
      - app-network

#  redis:
#    image: redis:7.0
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - app-network
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
